name: build
on:
  push:
    branches:
    - main
jobs:
  build:
    if: >
      !contains(github.event.head_commit.message, '#skip-ci')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.event.repository.full_name }}/${{ github.event.repository.name }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        tag_names: true
        cache: ${{ !contains(github.event.head_commit.message, '#no-cache') }}
